AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  gymDiarioLambda
  Sample SAM Template for gymDiarioLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 256
    Runtime: python3.12
    Architectures:
      - x86_64

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: SecretsManagerReadWrite
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
        - PolicyName: CognitoAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow

                Action:
                  - cognito-idp:AdminListGroupsForUser
                  - cognito-idp:AdminGetUser
                  - cognito-idp:ListUsers
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminCreateUser
                Resource: arn:aws:cognito-idp:us-east-1:010446714727:userpool/us-east-1_1HAjH1fKj

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable MySQL access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  MyDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MyDBCredentials
      Description: RDS MySQL credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'

  RelationalDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      DBName: Chomfit
      Engine: mysql
      EngineVersion: 8.0.35
      MasterUsername: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          - !Ref MyDBSecret
          - ':SecretString:username}}'
      MasterUserPassword: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          - !Ref MyDBSecret
          - ':SecretString:password}}'
      VPCSecurityGroups:
        - !GetAtt DatabaseSecurityGroup.GroupId

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
        - preferred_username
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      MfaConfiguration: 'OFF'
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Admin
      UserPoolId: !Ref UserPool
      Description: Grupo de administradores con permisos

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: User
      UserPoolId: !Ref UserPool
      Description: usuario regular

  CouchGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Couch
      UserPoolId: !Ref UserPool
      Description: Entrenadores

  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UserApi
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AuthApi
      StageName: Prod

  ExercisesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExercisesApi
      StageName: Prod

  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/getUserById/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /get_user_by_id
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  UpdateUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/updateUserData/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UpdateUserData:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /update_user
            Method: patch
            Auth:
              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  DisableUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/disableUser/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        DisableUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /disable_user
            Method: patch
            Auth:
              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  EnableUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/enableUser/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EnableUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /enable_user
            Method: patch
            Auth:
              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/login/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /login
            Method: post
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret
          CLIENT_ID: !GetAtt MyUserPoolClient.ClientId
          POOL_ID: !Ref UserPool

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/register/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /register
            Method: post
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  FindAllExercisesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: exercises/find_all/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        FindAllExercises:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /find_all_exercises
            Method: post
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  RegisterExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: exercises/register/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        RegisterExercise:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /register_exercise
            Method: post
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

  UpdateExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: exercises/update/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UpdateExercise:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /update_exercise
            Method: patch
      Environment:
        Variables:
          DB_HOST: !GetAtt RelationalDatabase.Endpoint.Address
          DB_NAME: Chomfit
          SECRET_NAME: !Ref MyDBSecret

Outputs:
  GetUserByIdApiUrl:
    Description: API Gateway endpoint URL with path get_user_by_id
    Value: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_user_by_id
  GetUserByIdFunctionArn:
    Description: Get data user Lambda Function ARN
    Value: !GetAtt GetUserByIdFunction.Arn
  UpdateUserDataApiUrl:
    Description: API Gateway endpoint URL with path update_user
    Value: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_user
  UpdateUserDataFunctionArn:
    Description: Update user data Lambda Function ARN
    Value: !GetAtt UpdateUserDataFunction.Arn
  DisableUserApiUrl:
    Description: API Gateway endpoint URL with path disable_user
    Value: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/disable_user
  DisableUserFunctionArn:
    Description: Disable user Lambda Function ARN
    Value: !GetAtt DisableUserFunction.Arn
  EnableUserApiUrl:
    Description: API Gateway endpoint URL with path enable_user
    Value: !Sub https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/enable_user
  EnableUserFunctionArn:
    Description: Enable user Lambda Function ARN
    Value: !GetAtt EnableUserFunction.Arn
  LoginApiUrl:
    Description: API Gateway endpoint URL with path login
    Value: !Sub https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login
  LoginFunctionArn:
    Description: Login Lambda Function ARN
    Value: !GetAtt LoginFunction.Arn
  RegisterApiUrl:
    Description: API Gateway endpoint URL with path register
    Value: !Sub https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register
  RegisterFunctionArn:
    Description: Register Lambda Function ARN
    Value: !GetAtt RegisterFunction.Arn
  FindAllExercisesApiUrl:
    Description: API Gateway endpoint URL with path find_all_exercises
    Value: !Sub https://${ExercisesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/find_all_exercises
  FindAllExercisesFunctionArn:
    Description: Find all exercises Lambda Function ARN
    Value: !GetAtt FindAllExercisesFunction.Arn
  RegisterExerciseApiUrl:
    Description: API Gateway endpoint URL with path register_exercise
    Value: !Sub https://${ExercisesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register_exercise
  RegisterExerciseFunctionArn:
    Description: Register exercise Lambda Function ARN
    Value: !GetAtt RegisterExerciseFunction.Arn
  UpdateExerciseApiUrl:
    Description: API Gateway endpoint URL with path update_exercise
    Value: !Sub https://${ExercisesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_exercise
  UpdateExerciseFunctionArn:
    Description: Update exercise Lambda Function ARN
    Value: !GetAtt UpdateExerciseFunction.Arn
  LambdaExecutionRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn